all: list queue_stack search sort tree graph-search

list:
	gcc -o list_c list.c
	./list_c
	g++ -o list_cpp list.cpp
	./list_cpp

queue_stack:
	g++ -o queue_stack queue_stack.cpp
	./queue_stack

search:
	python ./search.py

sort:
	python ./sort.py

tree:
	python ./traverse.py

graph-search:
	python ./bfs.py
	python ./dfs.py
	python ./dlfs.py

## homework

recursive_sort:
	python ./recursive_sort.py

calc:
	python ./calc.py

ids:
	python ./ids.py
